### PR TITLE
docs: require cryptography >= 42.0.0

### LINKED ISSUE #148: [3.5] AttributeError: 'builtins.Certificate' object has no attribute 'not_valid_after_utc'
Using `tls_certificates 3.5` I came across the error indicated in the SUBJECT.

This issue happens if no certficate request is present yet, and a `SecretNotFound` error is raised when the corresponding secret is to be accessed.

Then an attempt is made to create the request. However at this point the `not_valid_after_utc` attribute is referred, which is raising the error above.

The issue doesn't happen with 3.0 for sure (I didn't try further versions), I'm glad 3.0 works :sweat_smile: 

The full trace goes as below
```
unit-opensearch-dashboards-2: 09:21:59 ERROR unit.opensearch-dashboards/2.juju-log certificates:6: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-dashboards-2/charm/venv/ops/model.py", line 2955, in _run
    result = subprocess.run(args, **kwargs)  # type: ignore
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('/var/lib/juju/tools/unit-opensearch-dashboards-2/secret-get', '--label', 'afd8c2bccf834997afce12c2706d2ede------BEGIN CERTIFICATE REQUEST-----\nMIICizCCAXMCAQAwRjEVMBMGA1
UEAwwMMTAuNjcuMTQ3LjE1MS0wKwYDVQQtDCRh\nMjFkYmE2ZC03YjUxLTQxNjctODFmMS0yYTc4ZDYwODYzYmEwggEiMA0GCSqGSIb3\nDQEBAQUAA4IBDwAwggEKAoIBAQCaemwCLsCUTttzH1lV6gZh5u/4hS4DT0yiTclN\nq28dKwdoiiNt7DEP0SvymA0kba5fIwa1ETKVHqjm
HMAI3ma3TvQ5pD/rxWrco6Jd\nWx86p5cP2k8iIoyiekenvUgCsv3FefcdQs38l9EJ1pd29gRvF5nHbkXgAaznS0bR\n0qzwoUzfRa/dq31Fj4WO7J4AbItaHsLiBWMApde8J9SLHjZhc/PmS/HWAGlzjH1U\n7c/gfdPitDH56YM8ikQDqGHuiA/zzUNijer7u26P0oJtVxRNQMLpzm
Ln8csdfUV9\nm9NBDymBWnJlI6q6TsR0YzNVqzhrCFI7s7f9EsQizcukVyknAgMBAAGgADANBgkq\nhkiG9w0BAQsFAAOCAQEAUQXlPd6L3P6tHA94HReYBl3zBdAI85Cp1ziA0sVUE+Ik\n/RCl5YP6rJlaMV0nk/e7vou+9OAOAo5mLHZIN5STQ2ghoiuxcS86SJB5P1kIuzbI\nSV
dU99L1otYqLESSSRkMwD0VLnByFxy/FBLHGtN4tslR4lx6Iy44/ZyvUJHOnT6p\nmEUzDZoE5NHwKQ7yuiiVfUYOxScu0Wglk29OjQi/o2Vz4GSVvktVq1G9zCszMZFH\ng2PYA6sz03jD+GCsC470qcDaCeM+3T89YRf6OYA/6AiQ8CuB0h/EvN3I/SvGo723\nNe5MIdfENpCwu2nd
w/XK32nCBXtfu12vDa9+UnAOkg==\n-----END CERTIFICATE REQUEST-----', '--format=json')' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-dashboards-2/charm/venv/ops/model.py", line 3311, in secret_get
    result = self._run('secret-get', *args, return_output=True, use_json=True)
  File "/var/lib/juju/agents/unit-opensearch-dashboards-2/charm/venv/ops/model.py", line 2957, in _run
    raise ModelError(e.stderr) from e
ops.model.ModelError: ERROR consumer label "afd8c2bccf834997afce12c2706d2ede------BEGIN CERTIFICATE REQUEST-----\nMIICizCCAXMCAQAwRjEVMBMGA1UEAwwMMTAuNjcuMTQ3LjE1MS0wKwYDVQQtDCRh\nMjFkYmE2ZC03YjUxLTQxNjctODFmMS0y
YTc4ZDYwODYzYmEwggEiMA0GCSqGSIb3\nDQEBAQUAA4IBDwAwggEKAoIBAQCaemwCLsCUTttzH1lV6gZh5u/4hS4DT0yiTclN\nq28dKwdoiiNt7DEP0SvymA0kba5fIwa1ETKVHqjmHMAI3ma3TvQ5pD/rxWrco6Jd\nWx86p5cP2k8iIoyiekenvUgCsv3FefcdQs38l9EJ1pd29g
RvF5nHbkXgAaznS0bR\n0qzwoUzfRa/dq31Fj4WO7J4AbItaHsLiBWMApde8J9SLHjZhc/PmS/HWAGlzjH1U\n7c/gfdPitDH56YM8ikQDqGHuiA/zzUNijer7u26P0oJtVxRNQMLpzmLn8csdfUV9\nm9NBDymBWnJlI6q6TsR0YzNVqzhrCFI7s7f9EsQizcukVyknAgMBAAGgADAN
Bgkq\nhkiG9w0BAQsFAAOCAQEAUQXlPd6L3P6tHA94HReYBl3zBdAI85Cp1ziA0sVUE+Ik\n/RCl5YP6rJlaMV0nk/e7vou+9OAOAo5mLHZIN5STQ2ghoiuxcS86SJB5P1kIuzbI\nSVdU99L1otYqLESSSRkMwD0VLnByFxy/FBLHGtN4tslR4lx6Iy44/ZyvUJHOnT6p\nmEUzDZoE
5NHwKQ7yuiiVfUYOxScu0Wglk29OjQi/o2Vz4GSVvktVq1G9zCszMZFH\ng2PYA6sz03jD+GCsC470qcDaCeM+3T89YRf6OYA/6AiQ8CuB0h/EvN3I/SvGo723\nNe5MIdfENpCwu2ndw/XK32nCBXtfu12vDa9+UnAOkg==\n-----END CERTIFICATE REQUEST-----" not fou
nd


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-dashboards-2/charm/lib/charms/tls_certificates_interface/v3/tls_certificates.py", line 1777, in _on_relation_changed
    secret = self.model.get_secret(label=f"{LIBID}-{certificate.csr}")
  File "/var/lib/juju/agents/unit-opensearch-dashboards-2/charm/venv/ops/model.py", line 276, in get_secret
    content = self._backend.secret_get(id=id, label=label)
  File "/var/lib/juju/agents/unit-opensearch-dashboards-2/charm/venv/ops/model.py", line 3314, in secret_get
    raise SecretNotFoundError() from e
ops.model.SecretNotFoundError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-dashboards-2/charm/./src/charm.py", line 265, in <module>
    main(OpensearchDasboardsCharm)
  File "/var/lib/juju/agents/unit-opensearch-dashboards-2/charm/venv/ops/main.py", line 436, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-opensearch-dashboards-2/charm/venv/ops/main.py", line 144, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-opensearch-dashboards-2/charm/venv/ops/framework.py", line 351, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-opensearch-dashboards-2/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-opensearch-dashboards-2/charm/venv/ops/framework.py", line 942, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-opensearch-dashboards-2/charm/lib/charms/tls_certificates_interface/v3/tls_certificates.py", line 1786, in _on_relation_changed
    expire=self._get_next_secret_expiry_time(certificate.certificate),
  File "/var/lib/juju/agents/unit-opensearch-dashboards-2/charm/lib/charms/tls_certificates_interface/v3/tls_certificates.py", line 1809, in _get_next_secret_expiry_time
    expiry_time = _get_certificate_expiry_time(certificate)
  File "/var/lib/juju/agents/unit-opensearch-dashboards-2/charm/lib/charms/tls_certificates_interface/v3/tls_certificates.py", line 684, in _get_certificate_expiry_time
    return certificate_object.not_valid_after_utc
AttributeError: 'builtins.Certificate' object has no attribute 'not_valid_after_utc'
```

### PR DESCRIPTION
**Pull request by gruyaume**
# Description

Explicitly state in documentation that the tls lib requires charms to build with cryptography >= 42.0.0 (because we use `not_valid_after_utc`).

Fixes #148 

## Reference
- https://cryptography.io/en/latest/x509/reference/#cryptography.x509.Certificate.not_valid_after_utc

## Checklist

- [ ] My code follows the [style guidelines](/CONTRIBUTING.md) of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added tests that validate the behaviour of the software.
- [ ] I validated that new and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I have bumped the version of any required library.

### CODE REVIEW

**Review by Kayra1 — APPROVED** [review]

**Comment by gruyaume** [comment]
@Kayra1 as discussed during the dailies, the integration tests for juju 2.9 won't pass because of a bug in Juju 2.9.47 so we have been merging regardless of this failure.

**Comment by Kayra1** [comment]
Sorry, I thought this was because of the unit tests failing thing. Approved again.

**Review by Kayra1 — APPROVED** [review]
